server:
  port: 8080

spring:
  application:
    name: admin
  datasource:
    username: root
    password: root
  mvc:
    servlet:
      path: /admin

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/
    model: gemini-2.5-flash-lite

aws:
  secrets:
    name:
      gemini-api-key: geminiApiKey

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: ${spring.application.name}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/quick_stack
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://mysql:3306/quick_stack
  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://local-mysql:3306/quick_stack?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: validate
server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true