spring:
  application:
    name: admin

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/quick_stack
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    servlet:
      path: /api