spring:
  profiles:
    default: local
  datasource:
    username: root
    password: root

server:
  port: 8082
---

batch:
  cron:
    crawl: "0 0/1 * * * *"  # 1분마다

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/quick_stack
  jpa:
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://quick-stack.che2qyo4y77m.ap-northeast-2.rds.amazonaws.com:3306/quick_stack?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: none
# application-prod.yml
batch:
  cron:
    crawl: "0 0 0/1 * * *"  # 1시간마다


