server:
  port: 5500

---

spring:
  config:
    activate:
      on-profile: local

r2dbc:
  host: localhost
  port: 3306
  database: quick_stack
  username: root
  password: root

aws:
  secrets:
    name:
      github-release-token: local/github-release-token

discord:
  channel:
    github-release-notification: local/github-release-notification
    techblog-notification: local/techblog-notification

batch:
  cron:
    github-release: "0 */2 * * * *"
    tech-blog: "0 */2 * * * *"

---

spring:
  config:
    activate:
      on-profile: dev

r2dbc:
  host: localhost
  port: 3306
  database: quick_stack
  username: root
  password: root

aws:
  secrets:
    name:
      github-release-token: development/github-release-token

discord:
  channel:
    github-release-notification: development/github-release-notification
    techblog-notification: development/techblog-notification

batch:
  cron:
    github-release: "0 */2 * * * *"
    tech-blog: "0 */2 * * * *"

---

spring:
  config:
    activate:
      on-profile: prod

batch:
  cron:
    github-release: "0 0 */3 * * *"
    tech-blog: "0 0 */3 * * *"

r2dbc:
  host: quick-stack.che2qyo4y77m.ap-northeast-2.rds.amazonaws.com  # ← 변경
  port: 3306
  database: quick_stack
  username: admin
  password: ${DB_PASSWORD}

aws:
  secrets:
    name:
      github-release-token: production/github-release-token

discord:
  channel:
    github-release-notification: production/github-release-notification
    techblog-notification: production/techblog-notification