spring:
  application:
    name: batch
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 5500

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: ${spring.application.name}

---

spring:
  config:
    activate:
      on-profile: local

r2dbc:
  host: localhost
  port: 3306
  database: quick_stack
  username: root
  password: root

aws:
  secrets:
    name:
      github-release-token: local/github-release-token

discord:
  channel:
    github-release-notification: local/github-release-notification
    techblog-notification: local/techblog-notification

batch:
  cron:
    github-release: "0 */2 * * * *"
    tech-blog: "0 */2 * * * *"

---

spring:
  config:
    activate:
      on-profile: dev

r2dbc:
  host: localhost
  port: 3306
  database: quick_stack
  username: root
  password: root

aws:
  secrets:
    name:
      github-release-token: development/github-release-token

discord:
  channel:
    github-release-notification: development/github-release-notification
    techblog-notification: development/techblog-notification

batch:
  cron:
    github-release: "0 */2 * * * *"
    tech-blog: "0 */2 * * * *"

---

spring:
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: local-rabbitmq
    username: ${rabbitMQ_username}
    password: ${rabbitMQ_password}
batch:
  cron:
    github-release: "0 0 0 * * *"
    tech-blog: "0 0 0 * * *"

r2dbc:
  host: local-mysql
  port: 3306
  database: quick_stack
  username: ${DB_PASSWORD}
  password: ${DB_PASSWORD}

aws:
  secrets:
    name:
      github-release-token: production/github-release-token

discord:
  channel:
    github-release-notification: production/github-release-notification
    techblog-notification: production/techblog-notification