package com.project.batch.constants

enum class TechStack(val owner: String, val repo: String, val displayName: String, val en: String, val category: Category) {

    // Frontend
    REACT("facebook", "react", "React", "React", Category.FRONTEND),
    NEXT_JS("vercel", "next.js", "Next.js", "Next.js", Category.FRONTEND),
    VUE("vuejs", "core", "Vue.js", "Vue.js", Category.FRONTEND),
    ANGULAR("angular", "angular", "Angular", "Angular", Category.FRONTEND),
    TYPESCRIPT("microsoft", "TypeScript", "TypeScript", "TypeScript", Category.FRONTEND),
    VITE("vitejs", "vite", "Vite", "Vite", Category.FRONTEND),
    TAILWIND_CSS("tailwindlabs", "tailwindcss", "Tailwind CSS", "Tailwind CSS", Category.FRONTEND),
    TANSTACK_QUERY("TanStack", "query", "TanStack Query", "TanStack Query", Category.FRONTEND),
    SVELTE("sveltejs", "svelte", "Svelte", "Svelte", Category.FRONTEND),
    NUXT_JS("nuxt", "nuxt", "Nuxt.js", "Nuxt.js", Category.FRONTEND),
    ASTRO("withastro", "astro", "Astro", "Astro", Category.FRONTEND),
    ZUSTAND("pmndrs", "zustand", "Zustand", "Zustand", Category.FRONTEND),
    VITEST("vitest-dev", "vitest", "Vitest", "Vitest", Category.FRONTEND),

    // Backend
    SPRING_FRAMEWORK("spring-projects", "spring-framework", "Spring Framework", "Spring Framework", Category.BACKEND),
    SPRING_BOOT("spring-projects", "spring-boot", "Spring Boot", "Spring Boot", Category.BACKEND),
    SPRING_SECURITY("spring-projects", "spring-security", "Spring Security", "Spring Security", Category.BACKEND),
    SPRING_BATCH("spring-projects", "spring-batch", "Spring Batch", "Spring Batch", Category.BACKEND),
    SPRING_DATA_JPA("spring-projects", "spring-data-jpa", "Spring Data JPA", "Spring Data JPA", Category.BACKEND),
    SPRING_DATA_MONGODB("spring-projects", "spring-data-mongodb", "Spring Data MongoDB", "Spring Data MongoDB", Category.BACKEND),
    SPRING_DATA_REDIS("spring-projects", "spring-data-redis", "Spring Data Redis", "Spring Data Redis", Category.BACKEND),
    SPRING_AUTHORIZATION_SERVER("spring-projects", "spring-authorization-server", "Spring Authorization Server", "Spring Authorization Server", Category.BACKEND),
    SPRING_SESSION("spring-projects", "spring-session", "Spring Session", "Spring Session", Category.BACKEND),
    SPRING_KAFKA("spring-projects", "spring-kafka", "Spring Kafka", "Spring Kafka", Category.BACKEND),
    SPRING_AMQP("spring-projects", "spring-amqp", "Spring AMQP", "Spring AMQP", Category.BACKEND),
    SPRING_GRAPHQL("spring-projects", "spring-graphql", "Spring GraphQL", "Spring GraphQL", Category.BACKEND),
    SPRING_INTEGRATION("spring-projects", "spring-integration", "Spring Integration", "Spring Integration", Category.BACKEND),
    SPRING_CLOUD_GATEWAY("spring-cloud", "spring-cloud-gateway", "Spring Cloud Gateway", "Spring Cloud Gateway", Category.BACKEND),
    SPRING_CLOUD_CONFIG("spring-cloud", "spring-cloud-config", "Spring Cloud Config", "Spring Cloud Config", Category.BACKEND),
    SPRING_CLOUD_OPENFEIGN("spring-cloud", "spring-cloud-openfeign", "Spring Cloud OpenFeign", "Spring Cloud OpenFeign", Category.BACKEND),
    NEST_JS("nestjs", "nest", "NestJS", "NestJS", Category.BACKEND),
    FASTAPI("fastapi", "fastapi", "FastAPI", "FastAPI", Category.BACKEND),
    DJANGO("django", "django", "Django", "Django", Category.BACKEND),
    EXPRESS("expressjs", "express", "Express", "Express", Category.BACKEND),
    KAFKA("apache", "kafka", "Kafka", "Kafka", Category.BACKEND),
    REDIS("redis", "redis", "Redis", "Redis", Category.BACKEND),
    FLASK("pallets", "flask", "Flask", "Flask", Category.BACKEND),
    HONO("honojs", "hono", "Hono", "Hono", Category.BACKEND),
    GIN("gin-gonic", "gin", "Gin", "Gin", Category.BACKEND),
    FIBER("gofiber", "fiber", "Fiber", "Fiber", Category.BACKEND),
    PRISMA("prisma", "prisma", "Prisma", "Prisma", Category.BACKEND),

    // DevOps
    DOCKER("moby", "moby", "Docker", "Docker", Category.DEVOPS),
    KUBERNETES("kubernetes", "kubernetes", "Kubernetes", "Kubernetes", Category.DEVOPS),
    TERRAFORM("hashicorp", "terraform", "Terraform", "Terraform", Category.DEVOPS),
    AWS_CDK("aws", "aws-cdk", "AWS CDK", "AWS CDK", Category.DEVOPS),
    HELM("helm", "helm", "Helm", "Helm", Category.DEVOPS),
    ARGO_CD("argoproj", "argo-cd", "ArgoCD", "ArgoCD", Category.DEVOPS),
    GRAFANA("grafana", "grafana", "Grafana", "Grafana", Category.DEVOPS),
    PROMETHEUS("prometheus", "prometheus", "Prometheus", "Prometheus", Category.DEVOPS),
    ISTIO("istio", "istio", "Istio", "Istio", Category.DEVOPS),
    FLUX("fluxcd", "flux2", "Flux", "Flux", Category.DEVOPS),
    KUSTOMIZE("kubernetes-sigs", "kustomize", "Kustomize", "Kustomize", Category.DEVOPS),

    // Language
    PYTHON("python", "cpython", "Python", "Python", Category.LANGUAGE),
    GO("golang", "go", "Go", "Go", Category.LANGUAGE),
    RUST("rust-lang", "rust", "Rust", "Rust", Category.LANGUAGE),
    KOTLIN("JetBrains", "kotlin", "Kotlin", "Kotlin", Category.LANGUAGE),
    RUBY("ruby", "ruby", "Ruby", "Ruby", Category.LANGUAGE),
    ZIG("ziglang", "zig", "Zig", "Zig", Category.LANGUAGE),
    ELIXIR("elixir-lang", "elixir", "Elixir", "Elixir", Category.LANGUAGE),

    // AI
    LANGCHAIN("langchain-ai", "langchain", "LangChain", "LangChain", Category.AI),
    LANGGRAPH("langchain-ai", "langgraph", "LangGraph", "LangGraph", Category.AI),
    LLAMA_INDEX("run-llama", "llama_index", "LlamaIndex", "LlamaIndex", Category.AI),
    TRANSFORMERS("huggingface", "transformers", "Transformers", "Transformers", Category.AI),
    PYTORCH("pytorch", "pytorch", "PyTorch", "PyTorch", Category.AI),
    OLLAMA("ollama", "ollama", "Ollama", "Ollama", Category.AI),
    CREWAI("crewaiinc", "crewai", "CrewAI", "CrewAI", Category.AI),
    OPENAI_PYTHON("openai", "openai-python", "OpenAI Python", "OpenAI Python", Category.AI),
    VLLM("vllm-project", "vllm", "vLLM", "vLLM", Category.AI),
    LITELLM("BerriAI", "litellm", "LiteLLM", "LiteLLM", Category.AI),
    AUTOGEN("microsoft", "autogen", "AutoGen", "AutoGen", Category.AI),
    DSPY("stanfordnlp", "dspy", "DSPy", "DSPy", Category.AI),
    PYDANTIC_AI("pydantic", "pydantic-ai", "Pydantic AI", "Pydantic AI", Category.AI),
}