name: cd.yml

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      module:
        description: '배포할 모듈'
        required: true
        type: choice
        options:
          - api
          - admin
          - batch
          - crawler

      environment:
        description: '배포 환경'
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 권한 부여
        run: chmod +x gradlew

      - name: Jar 빌드
        run: ./gradlew :${{inputs.module}}:bootJar -x test

      - name: AWS 자격 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 도커 빌드& ECR 푸시
        run: |
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          REPOSITORY=${{ inputs.module }}
          IMAGE_TAG=${{ github.sha }}
          
          
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -t $REGISTRY/$REPOSITORY:latest \
            -f $REPOSITORY/Dockerfile $REPOSITORY
          
          
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest


      - name: dev 배포
        if: ${{ inputs.environment == 'dev' }}
        uses: appleboy/ssh-action@v1
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ inputs.module }}
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_USERNAME}}
          key: ${{ secrets.DEV_EC2_PEM }}
          envs: REGISTRY,REPOSITORY
          script: |
            /snap/bin/aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $REGISTRY
            if [ "$REPOSITORY" = "api" ]; then
              PORT=8081
            elif [ "$REPOSITORY" = "batch" ]; then
              PORT=5500
            elif [ "$REPOSITORY" = "admin" ]; then
              PORT=8080
            fi
            
            docker pull $REGISTRY/$REPOSITORY:latest
            docker stop $REPOSITORY || true
            docker rm $REPOSITORY|| true
            docker run -d \
              --name $REPOSITORY \
              -e SPRING_PROFILES_ACTIVE=dev \
              -p $PORT:$PORT \
              $REGISTRY/$REPOSITORY:latest

      - name: prod 배포
        if: ${{ inputs.environment == 'prod' }}
        run: |
          REGISTRY=${{steps.login-ecr.outputs.registry}}
          REPOSITORY=${{inputs.module}}
          DB_PASSWORD=${{secrets.PROD_DB_PASSWORD}}
      
          if [ "$REPOSITORY" = "api" ]; then
            PORT=8081
          elif [ "$REPOSITORY" = "batch" ]; then
            PORT=5500
          elif [ "$REPOSITORY" = "admin" ]; then
            PORT=8080
          elif [ "$REPOSITORY" = "crawler" ]; then
            PORT=8082
          fi
            
          if [ "$REPOSITORY" = "batch" ]; then
            DOCKER_CMD="docker run -d \
              --name $REPOSITORY \
              --network quick-stack \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e DB_PASSWORD=$DB_PASSWORD \
              -e rabbitMQ_username=${{ secrets.rabbitMQ_username }} \
              -e rabbitMQ_password=${{ secrets.rabbitMQ_password }} \
              $REGISTRY/$REPOSITORY:latest"
          else
            DOCKER_CMD="docker run -d \
              --name $REPOSITORY \
              --network quick-stack \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e SPRING_DATASOURCE_USERNAME=root \
              -e SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD \
              -e rabbitMQ_username=${{ secrets.rabbitMQ_username }} \
              -e rabbitMQ_password=${{ secrets.rabbitMQ_password }} \
              -p $PORT:$PORT \
              $REGISTRY/$REPOSITORY:latest"
          fi
          
          aws ssm send-command \
            --instance-ids ${{ secrets.PROD_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters commands="[\"/snap/bin/aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $REGISTRY\", 
              \"docker pull $REGISTRY/$REPOSITORY:latest\",
              \"docker stop $REPOSITORY || true\",
              \"docker rm $REPOSITORY || true\",
              \"docker system prune -f\",
              \"$DOCKER_CMD\"
            ]" \
            --region ap-northeast-2